### ISSUE TITLE
Clone a repository and its gitsubmoule using a template

### ISSUE THREAD

**Issue by buguibu** [buguibu/ios-notes-issues-lessons#26]
* Given a dependency stirred in a repository with gitsubmoules
* When I need to install it for build my product
* Then I can create a template for reuse this process as:

```parameters:
- name: azureRepoUrlName
  type: string
- name: branchTouse
  type: string

steps:
- task: PowerShell@2
  displayName: '🌳 Clone development pod'
  inputs:
    targetType: 'inline'
    script: |
      $header = "AUTHORIZATION: bearer $(System.AccessToken)"
      echo '🚧🌳 Fetching ${{ parameters.tfsRepoUrlName }}'
      git clone -c http.extraheader="$header" --branch ${{ parameters.branchTouse }} --depth 1 https://{{ORGANIZATION}}@dev.azure.com/{{ORGANIZATION}}/{{PROJECT}}/_git/${{ parameters. azureRepoUrlName }}
      echo '🚧🌳 Clone git submodules if needed'
      cd ./${{ parameters. azureRepoUrlName }}
      git -c http.extraheader="$header" submodule sync
      git -c http.extraheader="$header" submodule update --init --recursive --force --depth=1
```
* And make use of it as:
```
- template: ./devops/templates/clone_development_pod.yml
  parameters: 
    tfsRepoUrlName: DS-SDK-iOS
    branchTouse: develop
```
