### ISSUE TITLE
Set CURRENT_PROJECT_VERSION and MARKETING_VERSION on Azure Pipelines

### ISSUE THREAD

**Issue by buguibu** [buguibu/ios-notes-issues-lessons#28]
```
- task: Xcode@5
  inputs:
    actions: 'build'
    args: 'CURRENT_PROJECT_VERSION=${{ parameters.buildVersionToUse }} MARKETING_VERSION=${{ parameters.marketingVersionToUse }}' 
    scheme: '${{ parameters.appScheme }}'
```
