### ISSUE TITLE
Azure Pipelines templates

### ISSUE THREAD

**Issue by buguibu** [buguibu/ios-notes-issues-lessons#29]
# Parameter interpolation for make use of variables stores in templates
* Given a workspace with multiple targets
* When I try to build one from a single pipeline
* Then I need to store each target variable variants in a template file like:
```
variables:
  bundleId: com.wahtever...
  appStoreConnectAppId: '123456'
```
* for integrate it at the top of the pipeline as
```
variables:
- template: ./devops/templates/variables/${{ parameters.appScheme }}_variables.yml
```

# Set a variable based on a parameter
* Given a pipeline with a parameter
* When I want to use different values for a variable based on that parameter
* Then I can achieve that by doing the following:
```
stages:
- stage: Release
  jobs:
    - job: rootJob
      steps:
        - ${{ if eq(parameters.buildConfiguration, 'Release-Staging') }}:
          - script: echo "##vso[task.setvariable variable=googlePlistFilePrefix;]Staging"
        #
        - ${{ if eq(parameters.buildConfiguration, 'Release') }}:
          - script: echo "##vso[task.setvariable variable=googlePlistFilePrefix;]Production"
        # 
```
